#!/usr/bin/bash
alias tqtv="cd $HOME/Sites/dev/tomatocan"
alias mvim="/Applications/MacVim.app/Contents/bin/mvim"
alias githelp="cat $HOME/code/git-help.txt"
alias rt="rails test"
alias tc="cd $HOME/Sites/dev/tomatocan"
alias be="bundle exec"
alias sites="cd $HOME/Sites"
alias dev="cd $HOME/Sites/dev"
alias ls="ls -ap"
alias ll="ls -al"

alias dl="youtube-dl --extract-audio --audio-format mp3"
alias pgstart="postgres -D /usr/local/var/postgres"
alias tas="tmux attach-session"
alias be="bundle exec"

alias rcs="rails console --sandbox"
alias rc="rails console"
alias dms="rails db:migrate:status"
alias rr="rails routes"
alias pryrails="pry -r ./config/environment"

alias gst="git status"
alias gb="git branch"
alias gc="git commit"
alias gp="git push"
alias gco="git checkout"

alias symlink-gemfile="ln -s $HOME/Sites/dev/Gemfile $HOME/Sites/dev/tomatocan/"
alias cptv-master="https://github.com/ece106/tomatocan.git"

alias ..='cd ..'
alias ..2='cd ../../'
alias ..3='cd ../../../'
alias ..4='cd ../../../../'

alias lynda="cd $HOME/code/lynda"
alias udemy="cd $HOME/code/udemy"
alias pdfs="cd $HOME/Downloads/pdfs"
alias o="open"
alias aws-connect="ssh -i ~/Desktop/master-key-pai.pem ec2-user@54.172.116.241"

# REF: https://github.com/junegunn/fzf/wiki/Configuring-shell-key-bindings
# Using highlight (http://www.andre-simon.de/doku/highlight/en/highlight.html)
export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
